services:
  - type: web
    name: vendor-management
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
      - key: SERVER_PORT
        value: "10000"
