services:
  - type: web
    name: vendor-management
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
      - key: SERVER_PORT
        value: "10000"
      - key: DB_HOST
        fromDatabase:
          name: vendor-management-db
          property: connectionString
      - key: DB_PORT
        fromDatabase:
          name: vendor-management-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: vendor-management-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: vendor-management-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: vendor-management-db
          property: password

databases:
  - name: vendor-management-db
    plan: free
    region: oregon
